### ISSUE TITLE
Make sure Namespaces works with Merlin

### ISSUE THREAD

**Issue by aantron** [aantron/namespaces#3]
Add to the `README` any instructions that may be necessary for setup of Merlin+Namespaces in a project.

cc @ivg

**Comment by trefis** [comment]
Merlin dev here: merlin and namespaces should interact just fine.
(And it will be even sweeter if #4 is "fixed")

**Comment by aantron** [comment]
It doesn't quite yet work. I don't know enough about Merlin to be sure why, but it looks like Merlin is not following a `-no-alias-deps` module alias. Namely, if I have `Namespace.Foo.blah`, Merlin can find the module `Namespace`, and its nested module `Foo`, but not `Foo`'s item `blah`. This could be a problem in how Namepaces builds up modules, or in Merlin. @trefis initial thoughts?

**Comment by trefis** [comment]
What do you mean by "can't find"? What is actually failing?
Merlin is reporting errors? Or are you trying to get typing information? Or
to go to the definition?

**Comment by aantron** [comment]
Sorry, was referring to autocomplete. The autocomplete seems unable to list items of `Foo`.

**Comment by aantron** [comment]
I really mean to ask only if Merlin has any trouble with module aliases compiled with `-no-alias-deps` that you are already aware of. I will do a more thorough investigation after dealing with some other issues.

**Comment by trefis** [comment]
No, I am not aware of any and I do use module aliases on a daily basis.
Can you share your `.merlin`?

**Comment by aantron** [comment]
Ok, the problem was with me. I didn't know that the `S` and `B` directives don't apply recursively to subdirectories. Merlin works fine with Namespaces. I tested both Merlin within a project that uses Namespaces, and Merlin in a project that depends on a library that uses Namespaces. Apologies for the false alarm.
