### ISSUE TITLE
Better interaction with -short-paths

### ISSUE THREAD

**Issue by trefis** [aantron/namespaces#4]
When using the compiler, or Merlin, with `-short-paths` the typer when printing types will always select the "shortest" from all the aliases of a given type path.

The definition of shortest is (more or less): "the one with the less dots", e.g. `foobarbaz` (length = 1) is considered shorter than `X.y` (length = 2).
But there is a "penalty" mechanism on top of that: identifiers with a leading underscore or containing a double underscore incur a penalty of `+10`, i.e.
- `_foo` is of length `10`
- `Server__foo.t` is of length `11`

Why am talking about this? Because I think it would be nice if the `server/foo.ml` compiled to `server__foo.cmi` instead of `server_foo.cmi`. That way merlin users using `-short-paths` would always see `Server.Foo.t` when asking for a type and never `Server_foo.t` (which I believe no one ever wants to see).

The double underscore penalty will be present inside the compiler starting with version 4.03 (cf [Changes](https://github.com/ocaml/ocaml/blob/4.03/Changes#L54)), and is already present inside Merlin.

**Comment by aantron** [comment]
Already on it, thanks! :)

There is a second reason not to use single underscores, which is that the generated names can easily collide with names that have been chosen manually.

**Comment by aantron** [comment]
This should be fixed now. I don't have a proper test for this – I am still working out the testing framework. However, I have a private TODO for making sure the tests cover it somehow.
